import { fetchCommunications } from "@/src/lib/api";
import { getToken } from "@/src/lib/dal";
import { EmptyState } from "@/src/components/EmptyState";
import { KpiCard } from "@/src/components/KpiCard";
import { PageContainer } from "@/src/components/PageContainer";
import { PageHeader } from "@/src/components/PageHeader";
import { StatusBadge } from "@/src/components/StatusBadge";

type Communication = {
  id: string;
  entity_id: string;
  entity_name: string;
  type: string;
  recipient_id: string | null;
  recipient_name: string | null;
  channel: string;
  subject: string;
  delivery_status: string;
  sent_at: string | null;
  related_event_id: string | null;
  created_at: string;
};

function formatLabel(value: string | null) {
  return value ? value.replaceAll("_", " ") : "Not set";
}

function formatDate(value: string | null) {
  if (!value) {
    return "Not sent";
  }

  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

export default async function CommunicationsPage() {
  const token = await getToken();
  const response = await fetchCommunications(token ?? undefined);
  const communications: Communication[] = response.data;
  const sentCount = communications.filter(
    (communication) => communication.delivery_status === "sent"
  ).length;
  const latestCommunication = communications[0] ?? null;

  return (
    <PageContainer>
      <div className="space-y-6">
        <PageHeader
          variant="page"
          title="Communication Log"
          description="Review shareholder notifications and delivery evidence generated by governance events."
          badge={
            <div className="rounded-lg border border-slate-200 bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-500">
              Read-only
            </div>
          }
        />

        <section className="rounded-2xl bg-white p-4 shadow-sm sm:p-6">
        <div className="mb-8 grid gap-4 md:grid-cols-3">
          <KpiCard
            label="Total Communications"
            value={communications.length}
            detail="Logged notifications"
          />
          <KpiCard
            label="Sent"
            value={sentCount}
            detail="Delivered records"
            tone="success"
          />
          <KpiCard
            label="Latest Channel"
            value={
              latestCommunication
                ? formatLabel(latestCommunication.channel)
                : "No activity"
            }
            detail={
              latestCommunication
                ? formatDate(latestCommunication.sent_at)
                : "Not sent"
            }
          />
        </div>

        <div className="mb-8 rounded-xl border border-slate-200 bg-slate-50 p-5">
          <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 className="text-xl font-bold">Recent Notifications</h2>
              <p className="mt-1 text-sm text-slate-600">
                Latest outbound communication records from backend governance
                events.
              </p>
            </div>

            <span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-600 ring-1 ring-slate-200">
              {communications.length} records
            </span>
          </div>

          {communications.length > 0 ? (
            <div className="grid gap-4 lg:grid-cols-3">
              {communications.slice(0, 3).map((communication) => (
                <article
                  key={communication.id}
                  className="rounded-xl border border-slate-200 bg-white p-5"
                >
                  <div className="mb-4 flex items-start justify-between gap-3">
                    <div>
                      <p className="text-sm text-slate-500">
                        {communication.entity_name}
                      </p>
                      <h3 className="mt-1 text-lg font-bold capitalize text-slate-900">
                        {formatLabel(communication.type)}
                      </h3>
                    </div>

                    <StatusBadge status={communication.delivery_status} />
                  </div>

                  <dl className="space-y-3 text-sm">
                    <div>
                      <dt className="text-slate-500">Recipient</dt>
                      <dd className="font-semibold text-slate-900">
                        {communication.recipient_name || "Not linked"}
                      </dd>
                    </div>
                    <div>
                      <dt className="text-slate-500">Subject</dt>
                      <dd className="break-words text-slate-900">
                        {communication.subject}
                      </dd>
                    </div>
                    <div>
                      <dt className="text-slate-500">Sent At</dt>
                      <dd className="font-semibold text-slate-900">
                        {formatDate(communication.sent_at)}
                      </dd>
                    </div>
                  </dl>
                </article>
              ))}
            </div>
          ) : (
            <EmptyState
              title="No communications found"
              className="bg-white"
            />
          )}
        </div>

        <div className="overflow-x-auto rounded-xl border border-slate-200">
          {communications.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[960px] border-collapse text-left text-sm">
                <thead className="bg-slate-50">
                  <tr>
                    <th className="border-b border-slate-200 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Type</th>
                    <th className="border-b border-slate-200 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Recipient</th>
                    <th className="border-b border-slate-200 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Channel</th>
                    <th className="border-b border-slate-200 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Subject</th>
                    <th className="border-b border-slate-200 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Delivery</th>
                    <th className="border-b border-slate-200 px-4 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500">Sent At</th>
                  </tr>
                </thead>

                <tbody>
                  {communications.map((communication) => (
                    <tr key={communication.id} className="transition-colors hover:bg-slate-50">
                      <td className="border-b border-slate-100 px-4 py-3 font-medium capitalize">
                        {formatLabel(communication.type)}
                      </td>
                      <td className="border-b border-slate-100 px-4 py-3">
                        {communication.recipient_name || "Not linked"}
                      </td>
                      <td className="border-b border-slate-100 px-4 py-3 capitalize">
                        {formatLabel(communication.channel)}
                      </td>
                      <td className="border-b border-slate-100 px-4 py-3">
                        <span className="break-words">
                          {communication.subject}
                        </span>
                      </td>
                      <td className="border-b border-slate-100 px-4 py-3">
                        <StatusBadge status={communication.delivery_status} />
                      </td>
                      <td className="border-b border-slate-100 px-4 py-3">
                        {formatDate(communication.sent_at)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <div className="p-4">
              <EmptyState title="No communications found" />
            </div>
          )}
        </div>
        </section>
      </div>
    </PageContainer>
  );
}
